Tech.ECommerce.UI/Models/ErrorViewModel.cs
namespace Tech.ECommerce.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Tech.ECommerce.UI/Areas/AdminArea/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;

namespace Tech.ECommerce.UI.Areas.AdminArea.Controllers
{
    public class AuthController : Controller
    {
        public IActionResult Register()
        {
            return View();
        }
    }
}

Tech.ECommerce.UI/Areas/AdminArea/Controllers/ProductController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Tech.BusinessLogic.Abstract;
using Tech.BusinessLogic.Dtos;

namespace Tech.ECommerce.UI.Areas.AdminArea.Controllers
{
    [Area("AdminArea")]
    public class ProductController(IProductService productService,
                                   ICategoryService categoryService,
                                   IWebHostEnvironment webHostEnvironment) : Controller
    {
        private readonly IProductService _productService = productService;
        private readonly ICategoryService _categoryService = categoryService;
        private readonly IWebHostEnvironment _webHostEnvironment = webHostEnvironment;


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Product()
        {
            return View();
        }


        public async Task<IActionResult> GetProduct()
        {
            var products = await _productService.GetAllProduct();
            return Json(products);
        }


        public async Task<IActionResult> GetCategories()
        {
            var categories = await _categoryService.GetCategoryList();
            return Json(categories);
        }

        [HttpGet]
        public async Task<IActionResult> AddProduct([FromRoute] int? id = null)
        {
            if (id is not null)
            {
                var product = await _productService.GetProductByIdAsync(id.Value);
                return View(product);
            }

            return View(new ProductAddDto());
        }

        [HttpPost]
        public async Task<IActionResult> AddProduct([FromBody] ProductAddDto product)
        {

            if (ModelState.IsValid)
            {
                await _productService.AddProduct(product);
                return Json(new { message = "Product was added successfully!" });
                
            }

            return View(product);
           

        }



        [HttpGet]
        public async Task<IActionResult> RemoveProduct([FromRoute] int id )
        {
            await _productService.Remove(id);
            return Json(new { message = "Product was deleted successfully!" });
        }

        [HttpPost]
        public async Task<IActionResult> UploadImage(IFormFile image)
        {

            try
            {
                if (image is not null && image.Length > 0)
                {
                    string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "uploads");

                    string uniqeFileName = Guid.NewGuid().ToString() + "_" + image.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqeFileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await image.CopyToAsync(stream);
                    }

                    string imagePath = Path.Combine("/uploads", uniqeFileName);
                    string imageUrl = Url.Content(imagePath);


                    return Json(new { image = imageUrl });
                }
            }
            catch (Exception)
            {

                throw;
            }

            return Json(new { message = "Product was added successfully!" });
        }
    }
}

Tech.ECommerce.UI/Areas/AdminArea/ViewComponents/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Tech.ECommerce.UI.Areas.AdminArea.ViewComponents
{
    public class HeaderViewComponent:ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

Tech.ECommerce.UI/Areas/AdminArea/ViewComponents/SideBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Tech.ECommerce.UI.Areas.AdminArea.ViewComponents
{
    public class SideBarViewComponent: ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

Tech.ECommerce.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Tech.ECommerce.UI.Models;

namespace Tech.ECommerce.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Tech.ECommerce.UI/Areas/AdminArea/Views/Product/AddProduct.cshtml
@using Tech.BusinessLogic.Dtos
@model ProductAddDto
@{
    ViewData["Title"] = "AddProduct";
    Layout = "~/Areas/AdminArea/Views/Shared/_AdminLayout.cshtml";
}


<div asp-validation-summary="All"></div>
<div class="row">   
    <div class="col-lg-12">
        <div class="card ">
            <div class="card-body">
                <h5 class="card-title">Product Form</h5>
                <form id="product-form">
                    <input type="hidden"  id="product-id"  asp-for="Id" />
                    <div class="mb-3 ">
                        <label for="product-name" class="form-label pt-0">Name</label>
                        <div class="">
                            <input class="form-control" type="text" asp-for=Name  id="product-name" placeholder="Product name">
                            <span asp-validation-for="Name" class="mt-3 text-danger"></span>
                        </div>
                    </div>
                    <div class="mb-3 ">
                        <label for="product-price" class="form-label">Price</label>
                        <div class="">
                            <input class="form-control" type="number" asp-for=Price  id="product-price" placeholder="Price">
                            <span asp-validation-for="Price" class="mt-3 text-danger"></span>

                        </div>
                    </div>

                    <div class="mb-3 ">
                        <label for="product-image" class="form-label">Image</label>
                        <div class="">
                            <input class="form-control" type="file" asp-for=ImagePath  id="product-image" placeholder="Images">
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="product-description" class="form-label">Description</label>
                        <textarea class="form-control" id="product-description" asp-for=Description  rows="4" placeholder="Your Description"></textarea>
                    </div>


                    <input type="hidden" id="product-category-id"  asp-for="CategoryId" />
                    <div class="mb-3">
                        <select class="form-select" id="product-category">
                        </select>
                        <span asp-validation-for="CategoryId" class="mt-3 text-danger"></span>
                    </div>
                    <button type="button" class="btn btn-primary w-lg" id="add-product-btn">Create Product</button>
                </form>
            </div>
        </div>
        <!-- end card -->
    </div>
</div>



                   
@section scripts{
    <script src="~/js/product.js"></script>
}

Tech.ECommerce.UI/Areas/AdminArea/Views/Product/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/AdminArea/Views/Shared/_AdminLayout.cshtml";
}

<h1>Index</h1>

Tech.ECommerce.UI/Areas/AdminArea/Views/Product/Product.cshtml
@{
    ViewData["Title"] = "Product";
    Layout = "~/Areas/AdminArea/Views/Shared/_AdminLayout.cshtml";
}
 <div class="row">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="mb-0 font-size-18">Datatable</h4>
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Uniser E-Commerce</a></li>
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Product</a></li>
                    <li class="breadcrumb-item active">Product List</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Default Datatable</h5>
               
                <div class="table-responsive">
                    <div id="datatable_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
                      
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="product-datatable" class="table table-bordered dataTable no-footer table-striped " role="grid" aria-describedby="datatable_info">
                                    <thead class="bg-primary text-light">
                                        <tr role="row">
                                            <th class="sorting_asc" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 140.583px;">Id</th>
                                            <th class="sorting_asc" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 140.583px;">Product Name</th>
                                            <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 220.167px;">Price</th>
                                            <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-label="Age: activate to sort column ascending" style="width: 44.25px;">Category</th>
                                            <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 101.292px;">Description</th>
                                            <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 101.292px;">Image</th>
                                            <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 101.292px;">Edit</th>
                                            <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 101.292px;">Delete</th>
                                          
                                        </tr>
                                    </thead>
                                    <tbody>
                                      
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 col-md-5">
                                <div class="dataTables_info" id="datatable_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="modal fade bs-example-modal-center" tabindex="-1" aria-labelledby="mySmallModalLabel" style="display: none;" aria-hidden="true" id="image-modal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title align-self-center" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" id="close-modal-btn"></button>
            </div>
            <div class="modal-body">
               <img src="#" alt="Alternate Text" id="image-product" style="width:80%; object-fit:cover"/>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

@section scripts {
    <script src="~/AdminTemplates/libs/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/AdminTemplates/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/AdminTemplates/libs/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/AdminTemplates/libs/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js"></script>
    <script src="~/AdminTemplates/libs/jszip/jszip.min.js"></script>
    <script src="~/AdminTemplates/libs/pdfmake/build/pdfmake.min.js"></script>
    <script src="~/AdminTemplates/libs/pdfmake/build/vfs_fonts.js"></script>
    <script src="~/AdminTemplates/libs/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="~/AdminTemplates/libs/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="~/AdminTemplates/libs/datatables.net-buttons/js/buttons.colVis.min.js"></script>
    <script src="~/AdminTemplates/libs/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/AdminTemplates/libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js"></script>
    <script src="~/AdminTemplates/js/pages/datatables.init.js"></script>
    <script src="~/js/productTable.js"></script>
}

Tech.ECommerce.UI/Areas/AdminArea/Views/Shared/Components/Header/Default.cshtml
@{
    ViewData["Title"] = "Default";
}

<header id="page-topbar">
    <div class="navbar-header">
        <div class="d-flex">
            <!-- LOGO -->
            <div class="navbar-brand-box">
                <a href="index.html" class="logo logo-dark">
                    <span class="logo-sm">
                        <img src="/AdminTemplates/images/logo-dark.png" alt="" height="22">
                    </span>
                    <span class="logo-lg">
                        <img src="/AdminTemplates/images/logo-dark.png" alt="" height="17">
                    </span>
                </a>

                <a href="index.html" class="logo logo-light">
                    <span class="logo-sm">
                        <img src="/AdminTemplates/images/logo-sm.png" alt="" height="22">
                    </span>
                    <span class="logo-lg">
                        <img src="/AdminTemplates/images/logo-sm.png" alt="" height="17">
                    </span>
                </a>
            </div>

            <button type="button" class="btn btn-sm px-3 font-size-24 header-item waves-effect" id="vertical-menu-btn">
                <i class="mdi mdi-menu"></i>
            </button>
        </div>

        <!-- Search input -->
        <div class="search-wrap" id="search-wrap">
            <div class="search-bar">
                <input class="search-input form-control" placeholder="Search">
                <a href="#" class="close-search toggle-search" data-target="#search-wrap">
                    <i class="mdi mdi-close-circle"></i>
                </a>
            </div>
        </div>

        <div class="d-flex">
            <div class="dropdown d-none d-lg-inline-block">
                <button type="button" class="btn header-item toggle-search noti-icon waves-effect" data-target="#search-wrap">
                    <i class="mdi mdi-magnify"></i>
                </button>
            </div>

            <div class="dropdown d-inline-block d-lg-none ms-2">
                <button type="button" class="btn header-item noti-icon waves-effect" id="page-header-search-dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="mdi mdi-magnify"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end p-0" aria-labelledby="page-header-search-dropdown">

                    <form class="p-3">
                        <div class="m-0">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search ..." aria-label="Recipient's username">
                                <button class="btn btn-primary" type="submit"><i class="mdi mdi-magnify"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        

            <!-- Notification -->
            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item noti-icon waves-effect notification-step" id="page-header-notifications-dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="mdi mdi-bell-outline"></i>
                    <span class="badge bg-danger rounded-pill">2</span>
                </button>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end p-0" aria-labelledby="page-header-notifications-dropdown">
                    <div class="p-3">
                        <h6 class="m-0">Notifications (258) </h6>
                    </div>

                    <div data-simplebar="init" style="max-height: 230px;">
                        <div class="simplebar-wrapper" style="margin: 0px;">
                            <div class="simplebar-height-auto-observer-wrapper"><div class="simplebar-height-auto-observer"></div></div><div class="simplebar-mask">
                                <div class="simplebar-offset" style="right: 0px; bottom: 0px;">
                                    <div class="simplebar-content-wrapper" style="height: auto; overflow: hidden;">
                                        <div class="simplebar-content" style="padding: 0px;">
                                            <a href="#" class="text-reset notification-item">
                                                <div class="d-flex align-items-start">
                                                    <div class="avatar-xs me-3">
                                                        <span class="avatar-title bg-primary rounded-circle font-size-16">
                                                            <i class="mdi mdi-cart-outline"></i>
                                                        </span>
                                                    </div>
                                                    <div class="flex-1">
                                                        <h6 class="mb-1 font-size-15">Your order is placed</h6>
                                                        <div class="text-muted">
                                                            <p class="mb-1 font-size-12">
                                                                Dummy text of the printing and typesetting
                                                                industry.
                                                            </p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </a>

                                            <a href="#" class="text-reset notification-item">
                                                <div class="d-flex align-items-start">
                                                    <div class="avatar-xs me-3">
                                                        <span class="avatar-title bg-warning rounded-circle font-size-16">
                                                            <i class="mdi mdi-message"></i>
                                                        </span>
                                                    </div>
                                                    <div class="flex-1">
                                                        <h6 class="mb-1 font-size-15">New Message received</h6>
                                                        <div class="text-muted">
                                                            <p class="mb-1 font-size-12">You have 87 unread messages</p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </a>

                                            <a href="#" class="text-reset notification-item">
                                                <div class="d-flex align-items-start">
                                                    <div class="avatar-xs me-3">
                                                        <span class="avatar-title bg-info rounded-circle font-size-16">
                                                            <i class="mdi mdi-help"></i>
                                                        </span>
                                                    </div>
                                                    <div class="flex-1">
                                                        <h6 class="mb-1 font-size-15">Your order is placed</h6>
                                                        <div class="text-muted">
                                                            <p class="mb-1 font-size-12">
                                                                It is a long established fact that a reader will
                                                            </p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </a>

                                            <a href="#" class="text-reset notification-item">
                                                <div class="d-flex align-items-start">
                                                    <div class="avatar-xs me-3">
                                                        <span class="avatar-title bg-primary rounded-circle font-size-16">
                                                            <i class="mdi mdi-cart-outline"></i>
                                                        </span>
                                                    </div>
                                                    <div class="flex-1">
                                                        <h6 class="mb-1 font-size-15">Your order is placed</h6>
                                                        <div class="text-muted">
                                                            <p class="mb-1 font-size-12">
                                                                Dummy text of the printing and typesetting
                                                                industry.
                                                            </p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </a>

                                            <a href="#" class="text-reset notification-item">
                                                <div class="d-flex align-items-start">
                                                    <div class="avatar-xs me-3">
                                                        <span class="avatar-title bg-danger rounded-circle font-size-16">
                                                            <i class="mdi mdi-cart-outline"></i>
                                                        </span>
                                                    </div>
                                                    <div class="flex-1">
                                                        <h6 class="mb-1 font-size-15">Your order is placed</h6>
                                                        <div class="text-muted">
                                                            <p class="mb-1 font-size-12">
                                                                Dummy text of the printing and typesetting
                                                                industry.
                                                            </p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </a>

                                        </div>
                                    </div>
                                </div>
                            </div><div class="simplebar-placeholder" style="width: 0px; height: 0px;"></div>
                        </div><div class="simplebar-track simplebar-horizontal" style="visibility: hidden;"><div class="simplebar-scrollbar" style="transform: translate3d(0px, 0px, 0px); display: none;"></div></div><div class="simplebar-track simplebar-vertical" style="visibility: hidden;"><div class="simplebar-scrollbar" style="transform: translate3d(0px, 0px, 0px); display: none;"></div></div>
                    </div>
                    <div class="p-2 border-top d-grid">
                        <a class="btn btn-sm btn-link font-size-14 btn-block text-center" href="javascript:void(0)">
                            <i class="mdi mdi-arrow-right-circle me-1"></i> View all
                        </a>
                    </div>
                </div>
            </div>


            <!-- User -->
            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item waves-effect user-step" id="page-header-user-dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="rounded-circle header-profile-user" src="/AdminTemplates/images/users/user-1.jpg" alt="Header Avatar">
                    <span class="d-none d-xl-inline-block ms-1">Amelia</span>
                    <i class="mdi mdi-chevron-down d-none d-xl-inline-block"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-end">
                    <!-- item-->
                    <a class="dropdown-item" href="#">
                        <i class="dripicons-user d-inline-block text-muted me-2"></i>
                        Profile
                    </a>
                    <a class="dropdown-item" href="#">
                        <i class="dripicons-wallet d-inline-block text-muted me-2"></i> My
                        Wallet
                    </a>
                    <a class="dropdown-item d-block" href="#"><i class="dripicons-gear d-inline-block text-muted me-2"></i> Settings</a>
                    <a class="dropdown-item" href="#">
                        <i class="dripicons-lock d-inline-block text-muted me-2"></i> Lock
                        screen
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">
                        <i class="dripicons-exit d-inline-block text-muted me-2"></i>
                        Logout
                    </a>
                </div>
            </div>

          

        </div>
    </div>
</header>

Tech.ECommerce.UI/Areas/AdminArea/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link href="~/admintemplates/css/icons.min.css" rel="stylesheet" />
    <link href="~/AdminTemplates/libs/metrojs/release/MetroJs.Full/MetroJs.min.css" rel="stylesheet" type="text/css" />
    <link href="~/AdminTemplates/css/bootstrap.min.css" id="bootstrap-style" rel="stylesheet" type="text/css" />
    <!-- Icons Css -->
    <link href="~/AdminTemplates/css/icons.min.css" rel="stylesheet" type="text/css" />
    <!-- App Css-->
    <link href="~/AdminTemplates/css/app.min.css" id="app-style" rel="stylesheet" type="text/css" />
    <link href="~/admintemplates/libs/sweetalert2/sweetalert2.min.css" rel="stylesheet" />
</head>
<body data-topbar="dark">


    <div id="layout-wrapper">
        @await Component.InvokeAsync("Header")
        @await Component.InvokeAsync("SideBar")
        <div class="main-content">
            <div class="page-content">
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
    <!-- JAVASCRIPT -->
    <script src="~/AdminTemplates/libs/jquery/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/AdminTemplates/libs/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/AdminTemplates/libs/metismenu/metisMenu.min.js"></script>
    <script src="~/AdminTemplates/libs/simplebar/simplebar.min.js"></script>
    <script src="~/AdminTemplates/libs/node-waves/waves.min.js"></script>
    <script src="~/admintemplates/libs/sweetalert2/sweetalert2.min.js"></script>
    <!--Morris Chart-->

    <script src="~/AdminTemplates/libs/morris.js/morris.min.js"></script>
    <script src="~/AdminTemplates/libs/raphael/raphael.min.js"></script>
    <script src="~/AdminTemplates/libs/jquery-knob/jquery.knob.min.js"></script>
    <script src="~/AdminTemplates/libs/metrojs/release/MetroJs.Full/MetroJs.min.js"></script>

    <script src="~/AdminTemplates/js/pages/dashboard.init.js"></script>

    <script src="~/AdminTemplates/js/app.js"></script>
    

    @await RenderSectionAsync("scripts", false);
</body>
</html>

Tech.ECommerce.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>